### ISSUE TITLE
Setup routes with the main layout and heading

### ISSUE THREAD

**Issue by chirag3003** [chirag3003/project-maple#11]
Setup these routes
- Dashboard(/)
- Store (/store)
- Create (/create)
- Logs (/logs)
- Services (/services)

Setup the Mainlayout and Seo component in each route and add a heading for each of them

**Comment by v0nser** [comment]
Please assign it to me. @chirag3003

**Comment by chirag3003** [comment]
Ok @v0nser go on

**Comment by chirag3003** [comment]
@v0nser Please open a pull request to the dev branch when you are done with your work

**Comment by chirag3003** [comment]
@v0nser any progress?

**Comment by v0nser** [comment]
> @v0nser any progress?

Yes, debugging the errors.
