### ISSUE TITLE
Create UI for Pastebin Section

### ISSUE THREAD

**Issue by BRAVO68WEB** [chirag3003/project-maple#26]
- Create UI component for PasteBin section

**Comment by najeebkp** [comment]
Hi @BRAVO68WEB  please assign this to me

**Comment by BRAVO68WEB** [comment]
Sure Go ahead

**Comment by najeebkp** [comment]
@BRAVO68WEB  can you elaborate a little bit what exactly need to be done?

**Comment by BRAVO68WEB** [comment]
CC @chirag3003

**Comment by chirag3003** [comment]
@najeebkp pull the dev branch and make a new branch feature/pastebin. Create a route /pastebin and work on it
Pastebin is a site where people can paste there text and share it with others with a link. We are looking for a similar feature
https://pastebin.com/

You just have to create a simple ui for this feature
- A text area
- A save button
- A share button

Make sure the ui design matches with the other designs
