### ISSUE TITLE
Improve the frontend UI

### ISSUE THREAD

**Issue by DarkFalc0n** [chirag3003/project-maple#31]
The frontend of the project needs the following improvements: 
- Improve dashboard components.
-  Implement a coherent color scheme and font hierarchy.
-  Follow a responsive UI scheme and make the web-app accessible on multiple platforms.

**Comment by chirag3003** [comment]
Go on @DarkFalc0n

**Comment by chirag3003** [comment]
@DarkFalc0n great job
Can you please help this developer by improving the pastebin ui too. I would really appreciate it

**Comment by DarkFalc0n** [comment]
@chirag3003 Sure, I will implement a consistent UI design in the pastebin page too.

**Comment by chirag3003** [comment]
Thank you sir

**Comment by DarkFalc0n** [comment]
@chirag3003 I have implemented similar UI for pastebin. Please check.
