### ISSUE TITLE
Create the Profile card for the user

### ISSUE THREAD

**Issue by chirag3003** [chirag3003/project-maple#7]
- create a component ProfileCard
- place the component in its position

**Comment by cenacrharsh** [comment]
I would like to work on this issue. Please assign it to me @chirag3003.

**Comment by chirag3003** [comment]
@cenacrharsh Unfortunately this issue already over but stay tuned for upcoming issues . We will post lots of issues very soon

**Comment by chirag3003** [comment]
This issue has been completed by #10

**Comment by ayushsarode** [comment]
Hey! I wanna add Readme.md And Contributing.md Files.
Can I?

**Comment by chirag3003** [comment]
#10

**Comment by chirag3003** [comment]
> 

@AyushSarode stay tuned , we will be posting issues for that
